<a href="https://colab.research.google.com/github/KarbivnychyiVolodymyr/machine_learning/blob/main/%D0%9A%D0%B0%D1%80%D0%B1%D1%96%D0%B2%D0%BD%D0%B8%D1%87%D0%B8%D0%B9_%D0%BF%D1%80_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

варіант 13

In [ ]:
'''Завдання 1
Створіть одновимірний масив (вектор) зі зростаючою геометричною прогресією, де
кожне наступне число більше попереднього в 2 рази, починаючи з 2, та виведіть його
значення'''

import numpy as np

vector = np.array([2**i for i in range(15)])
print(vector)


[    1     2     4     8    16    32    64   128   256   512  1024  2048
  4096  8192 16384]


In [ ]:
'''Завдання 2
Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його оберненими
значеннями натуральних чисел, починаючи з 1, та виведіть його значення.'''

import numpy as np

matrix = 1 / np.arange(1, 10).reshape(3, 3)
print(matrix)


[[1.         0.5        0.33333333]
 [0.25       0.2        0.16666667]
 [0.14285714 0.125      0.11111111]]


In [ ]:
'''Завдання 3
Створіть масив розміром 3x3, заповніть його випадковими дійсними числами в
діапазоні від -3 до 3 та знайдіть максимальний елемент'''

import numpy as np

matrix = np.random.uniform(-3, 3, (3, 3))
max_element = np.max(matrix)

print(matrix)
print("Максимальний елемент:", max_element)


[[ 2.00811794  1.16790542 -2.41660925]
 [-2.62051285 -0.01934719  2.22883133]
 [ 1.89166089 -1.20488842  0.50666553]]
Максимальний елемент: 2.2288313275172493


In [ ]:
'''Завдання 4
Створіть масив розміром 3x3, заповніть його випадковими дійсними числами в
діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного
стовпця, менших за 0.5.'''

import numpy as np

matrix = np.random.uniform(0, 1, (3, 3))
vector = np.sum(matrix * (matrix < 0.5), axis=0)

print(matrix)
print("Вектор-стовпчик із сумами елементів, менших за 0.5:", vector)


[[0.8327666  0.86262428 0.21123408]
 [0.77758024 0.61186016 0.92255141]
 [0.46725819 0.34007158 0.94967417]]
Вектор-стовпчик із сумами елементів, менших за 0.5: [0.46725819 0.34007158 0.21123408]


In [ ]:
'''Завдання 5
Створіть два одновимірних масиви розміром 6, заповніть їх випадковими дійсними
числами від -2 до 2 та виконайте на них поелементні операції додавання, віднімання
та множення'''

import numpy as np

array1 = np.random.uniform(-2, 2, 6)
array2 = np.random.uniform(-2, 2, 6)

addition = array1 + array2
subtraction = array1 - array2
multiplication = array1 * array2

print("Масив 1:", array1)
print("Масив 2:", array2)
print("Додавання:", addition)
print("Віднімання:", subtraction)
print("Множення:", multiplication)


Масив 1: [-0.12599378 -1.56850528 -1.19072853 -0.13679117  0.10423816 -1.65022205]
Масив 2: [ 0.01963057  1.41199448 -1.20795266 -1.20040722 -1.21943449  1.08681491]
Додавання: [-0.10636322 -0.1565108  -2.39868119 -1.33719839 -1.11519633 -0.56340714]
Віднімання: [-0.14562435 -2.98049975  0.01722414  1.06361605  1.32367265 -2.73703697]
Множення: [-0.00247333 -2.21472079  1.4383437   0.16420511 -0.12711161 -1.79348594]


In [ ]:
'''Завдання 6
Створіть дві матриці 4x4, заповніть їх довільними цілими числами від 1 до 5 та
знайдіть їх добуток.'''

import numpy as np

matrix1 = np.random.randint(1, 6, (4, 4))
matrix2 = np.random.randint(1, 6, (4, 4))

product = np.dot(matrix1, matrix2)

print("Матриця 1:")
print(matrix1)
print("Матриця 2:")
print(matrix2)
print("Добуток матриць:")
print(product)


Матриця 1:
[[1 4 5 4]
 [2 3 1 5]
 [2 4 1 2]
 [4 1 5 3]]
Матриця 2:
[[1 2 4 2]
 [5 1 2 4]
 [5 3 4 3]
 [4 1 1 5]]
Добуток матриць:
[[62 25 36 53]
 [42 15 23 44]
 [35 13 22 33]
 [46 27 41 42]]


In [ ]:
'''Завдання 7
Створіть дві матриці розміром 3x2 та 2x2, заповніть їх випадковими цілими числами
в діапазоні від 1 до 8 та перемножте їх між собою.'''
import numpy as np

matrix1 = np.random.randint(1, 9, (3, 2))
matrix2 = np.random.randint(1, 9, (2, 2))

product = np.dot(matrix1, matrix2)

print("Матриця 1:")
print(matrix1)
print("Матриця 2:")
print(matrix2)
print("Добуток матриць:")
print(product)


Матриця 1:
[[2 7]
 [7 6]
 [1 5]]
Матриця 2:
[[3 4]
 [8 2]]
Добуток матриць:
[[62 22]
 [69 40]
 [43 14]]


In [ ]:
'''Завдання 8
Створіть матрицю розміром 2x2, заповніть її випадковими цілими числами в діапазоні
від 1 до 15 та знайдіть її обернену матрицю.'''

import numpy as np

matrix = np.random.randint(1, 16, (2, 2))
inverse_matrix = np.linalg.inv(matrix)

print("Матриця:")
print(matrix)
print("Обернена матриця:")
print(inverse_matrix)


Матриця:
[[1 8]
 [8 4]]
Обернена матриця:
[[-0.06666667  0.13333333]
 [ 0.13333333 -0.01666667]]


In [ ]:
'''Завдання 9
Створіть матрицю розміром 7x3, заповніть її випадковими дійсними числами в
діапазоні від 0 до 1 та транспонуйте її.'''

import numpy as np

matrix = np.random.uniform(0, 1, (7, 3))
transposed_matrix = np.transpose(matrix)

print("Матриця:")
print(matrix)
print("Транспонована матриця:")
print(transposed_matrix)


Матриця:
[[0.36696995 0.08055804 0.51685052]
 [0.1497519  0.95250632 0.90297543]
 [0.00502036 0.44198141 0.31885683]
 [0.77824762 0.26067313 0.86831501]
 [0.9370119  0.51790502 0.27151507]
 [0.18106808 0.34360996 0.6706152 ]
 [0.64175228 0.36659548 0.97222291]]
Транспонована матриця:
[[0.36696995 0.1497519  0.00502036 0.77824762 0.9370119  0.18106808
  0.64175228]
 [0.08055804 0.95250632 0.44198141 0.26067313 0.51790502 0.34360996
  0.36659548]
 [0.51685052 0.90297543 0.31885683 0.86831501 0.27151507 0.6706152
  0.97222291]]


In [ ]:
'''Завдання 10
Створіть матрицю розміром 3x4 та вектор розміром 4x1, заповніть матрицю
випадковими цілими числами в діапазоні від 1 до 10, а вектор - випадковими дійсними
числами від 0 до 1, і знайдіть добуток матриці на вектор.'''

import numpy as np

matrix = np.random.randint(1, 11, (3, 4))
vector = np.random.uniform(0, 1, (4, 1))

product = np.dot(matrix, vector)

print("Матриця:")
print(matrix)
print("Вектор:")
print(vector)
print("Добуток матриці на вектор:")
print(product)


Матриця:
[[ 9  2  2  7]
 [ 2  8  6  1]
 [ 4  7  9 10]]
Вектор:
[[0.8610647 ]
 [0.6226721 ]
 [0.39418334]
 [0.30935464]]
Добуток матриці на вектор:
[[11.94877564]
 [ 9.37796091]
 [14.44415998]]


In [ ]:
'''Завдання 11
Створіть матрицю розміром 2x3 та вектор розміром 3x1, заповніть матрицю
випадковими дійсними числами від 0 до 1, а вектор - випадковими дійсними числами
від 0 до 1, і знайдіть добуток матриці на вектор.'''

import numpy as np

matrix = np.random.uniform(0, 1, (2, 3))
vector = np.random.uniform(0, 1, (3, 1))

product = np.dot(matrix, vector)

print("Матриця:")
print(matrix)
print("Вектор:")
print(vector)
print("Добуток матриці на вектор:")
print(product)


Матриця:
[[0.16285305 0.48614708 0.77422695]
 [0.14155719 0.18587873 0.82612108]]
Вектор:
[[0.73337877]
 [0.86916643]
 [0.18124701]]
Добуток матриці на вектор:
[[0.68230202]
 [0.41510656]]


In [ ]:
'''Завдання 12
Створіть дві матриці розміром 6x6, заповніть їх випадковими цілими числами в
діапазоні від 1 до 10 та знайдіть їхню суму.'''

import numpy as np

matrix1 = np.random.randint(1, 11, (6, 6))
matrix2 = np.random.randint(1, 11, (6, 6))

sum_matrix = matrix1 + matrix2

print("Матриця 1:")
print(matrix1)
print("Матриця 2:")
print(matrix2)
print("Сума матриць:")
print(sum_matrix)


Матриця 1:
[[ 9  9  3  5  3 10]
 [ 9  1  6  2  1  3]
 [10  7  8 10 10  8]
 [ 6  9  1  8  2  7]
 [ 6  7  8  9 10  8]
 [ 9  8  7  2  6 10]]
Матриця 2:
[[ 8  4  8  5  3  9]
 [ 7  1  6  8  4  4]
 [ 6  6  5  9  3  3]
 [ 1  7  4  1 10  1]
 [ 3  8  2  5  9  3]
 [ 8  9  3 10  9 10]]
Сума матриць:
[[17 13 11 10  6 19]
 [16  2 12 10  5  7]
 [16 13 13 19 13 11]
 [ 7 16  5  9 12  8]
 [ 9 15 10 14 19 11]
 [17 17 10 12 15 20]]


In [ ]:
'''Завдання 13
Створіть дві матриці розміром 3x3, заповніть їх випадковими дійсними числами в
діапазоні від 0 до 1 та знайдіть добуток їх елементів'''

import numpy as np

matrix1 = np.random.uniform(0, 1, (3, 3))
matrix2 = np.random.uniform(0, 1, (3, 3))

product_elements = np.multiply(matrix1, matrix2)

print("Матриця 1:")
print(matrix1)
print("Матриця 2:")
print(matrix2)
print("Добуток елементів матриць:")
print(product_elements)


Матриця 1:
[[0.55472713 0.17034887 0.64878342]
 [0.82414887 0.5982308  0.83480623]
 [0.33813919 0.40299648 0.51788183]]
Матриця 2:
[[0.5832721  0.64730587 0.72164071]
 [0.61528826 0.71328487 0.38192905]
 [0.15542973 0.15792849 0.33734025]]
Добуток елементів матриць:
[[0.32355686 0.11026783 0.46818853]
 [0.50708912 0.42670898 0.31883675]
 [0.05255688 0.06364462 0.17470238]]


In [ ]:
'''Завдання 14
Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в
діапазоні від -5 до 5 та знайдіть суму елементів матриці, які більше за їх середнє
арифметичне значення.'''

import numpy as np

matrix = np.random.uniform(-5, 5, (3, 3))

mean_value = np.mean(matrix)
sum_above_mean = np.sum(matrix[matrix > mean_value])

print("Матриця:")
print(matrix)
print("Середнє арифметичне значення:")
print(mean_value)
print("Сума елементів, які більше за середнє арифметичне значення:")
print(sum_above_mean)


Матриця:
[[-4.49454672  1.12186716 -0.06416052]
 [-0.15346236 -3.87120648  2.787767  ]
 [ 4.3867995   1.69692483  2.85135469]]
Середнє арифметичне значення:
0.47348189948782754
Сума елементів, які більше за середнє арифметичне значення:
12.844713174080013


In [ ]:
'''Завдання 15
Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в
діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить найменше ціле значення
в кожному рядку матриці.'''

import numpy as np

matrix = np.random.uniform(0, 1, (3, 3))
min_in_rows = np.floor(np.min(matrix, axis=1))

print("Матриця:")
print(matrix)
print("Вектор-стовпчик з найменшими цілими значеннями в кожному рядку:")
print(min_in_rows)


Матриця:
[[0.57926524 0.94811093 0.61032466]
 [0.24761678 0.48081797 0.75895966]
 [0.2011009  0.92704247 0.40934676]]
Вектор-стовпчик з найменшими цілими значеннями в кожному рядку:
[0. 0. 0.]


In [ ]:
'''висновок
У результаті виконання лабораторної роботи було створено та оброблено
різноманітні масиви та матриці за допомогою бібліотеки NumPy. Я навчився
генерувати випадкові числа в заданих діапазонах, виконувати поелементні
операції, а також використовувати функції для обчислення статистичних показників
та виконання матричних обчислень. Зокрема, було освоєно створення обернених матриць,
знаходження добутків матриць і сумування елементів за певними критеріями. Ці
навички є основою для подальшого аналізу даних і чисельних обчислень у наукових
та інженерних задачах.
'''

'висновок'